"""Build Wave Lab v4 (RAM): DUTY hysteresis + glide, loudness and DC matching.

Two-stage build:
1. Compile waves.c for the host (x86-64 DLL) with a placeholder level table and
   measure every wave at every DUTY value (mean, RMS, peak) with the module's own
   math, at reference pitches C3/C4/C5/C6.
2. Write wave_level.h (DC + peak-capped RMS-matching gain per wave and DUTY),
   compile for the SP at 0x8353E400 and lay the image out exactly like v3-ram
   (SDRAM copy row after zero-init, pool base moved past the module).

Base: firmware/doom-poly-v4-releasefix (hash-checked). Output:
firmware/doom-poly-waves-v4-ram/. Nothing is flashed or uploaded.

    python waves_v4_ram/build_v4.py          (from the sp404mk2 folder)
"""
import ctypes
import hashlib
import json
import math
import os
import shutil
import struct
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT / 'waves_v3_ram'))
import build_ram as v3  # noqa: E402  (image layout, gates, guards, ELF reader)

OUT = ROOT / 'firmware' / 'doom-poly-waves-v4-ram'
TABLES_SHA = '8d59eb235dc4dcb69906f91f17547ebfe9bc2c2f71e9002162f3995a9bdfb2b9'
TARGET_RMS, PEAK_MAX, GAIN_MAX = 0.5, 0.98, 8.0
REF_NOTES = (48, 60, 72, 84)          # MIDI C3..C6; C4 sets DC and RMS
N_PHASES = 4096
ZIG_ENV = dict(os.environ, ZIG_GLOBAL_CACHE_DIR=str(HERE / '.zig-cache'),
               ZIG_LOCAL_CACHE_DIR=str(HERE / '.zig-cache'))
COMMON = ['-O2', '-ffreestanding', '-fno-builtin', '-fno-stack-protector', '-ffp-contract=off',
          '-ffunction-sections', '-fdata-sections', '-fno-unwind-tables',
          '-fno-asynchronous-unwind-tables']


def cfloat(x):
    return float(struct.unpack('<f', struct.pack('<f', x))[0]).hex() + 'f'


def write_level_header(levels):
    rows = []
    for per_type in levels:
        rows.append('{' + ','.join('{%s,%s}' % (cfloat(m), cfloat(g)) for m, g in per_type) + '}')
    text = ('// Generated by build_v4.py: {mean, gain} per wave (TYPE 15..31) and DUTY 0..100.\n'
            'static const float wave_level[17][101][2] = {\n' + ',\n'.join(rows) + '\n};\n')
    (HERE / 'wave_level.h').write_text(text, encoding='ascii', newline='\n')
    return hashlib.sha256(text.encode()).hexdigest()


def host_dll():
    out = HERE / 'build' / 'host'
    out.mkdir(parents=True, exist_ok=True)
    dll = out / 'waves_host.dll'
    subprocess.run([str(v3.ZIG), 'cc', '-target', 'x86_64-windows-gnu', '-shared', '-DWAVE_HOST',
                    *COMMON, '-I', str(HERE), str(HERE / 'waves.c'), '-o', str(dll)],
                   check=True, cwd=HERE, env=ZIG_ENV)
    lib = ctypes.CDLL(str(dll))
    lib.wave_host_stats.argtypes = [ctypes.c_uint, ctypes.c_float, ctypes.c_float, ctypes.c_int,
                                    ctypes.POINTER(ctypes.c_float), ctypes.c_int, ctypes.c_float,
                                    ctypes.c_int, ctypes.POINTER(ctypes.c_float)]
    return lib


def measure(lib):
    """Return levels[type][duty] = (mean, gain) and a report row per wave."""
    dts = [440 * 2 ** ((n - 69) / 12) / 48000 for n in REF_NOTES]
    levels, report = [], []
    out = (ctypes.c_float * 3)()
    for kind in range(15, 32):
        rs = [i / 10 - 1 for i in range(21)] if kind == 31 else [0.0]
        rarr = (ctypes.c_float * len(rs))(*rs)
        per_type = []
        for duty in range(101):
            lib.wave_host_stats(kind, duty, dts[1], N_PHASES, rarr, len(rs), 0, 0, out)
            mean, rms = out[0], out[1]
            peak = 0.0
            for dt in dts:
                lib.wave_host_stats(kind, duty, dt, N_PHASES, rarr, len(rs), mean, 1, out)
                peak = max(peak, out[2])
            gain = min(TARGET_RMS / max(rms, 1e-6), PEAK_MAX / max(peak, 1e-6), GAIN_MAX)
            per_type.append((mean, gain))
            if duty in (0, 50, 100):
                report.append((kind, duty, mean, rms, peak, gain, min(gain * rms, TARGET_RMS)))
        levels.append(per_type)
    return levels, report


def compile_arm():
    folder = HERE / 'build' / 'ram'
    folder.mkdir(parents=True, exist_ok=True)
    (folder / 'waves.ld').write_text(v3.LINKER.format(base=v3.LINK_BASE), encoding='ascii', newline='\n')
    subprocess.run([str(v3.ZIG), 'cc', '-target', 'thumb-freestanding-eabihf',
                    '-mcpu=cortex_m7+vfp4d16', '-mfpu=vfpv4-d16', '-mfloat-abi=hard', *COMMON,
                    '-nostdlib', '-Wl,--no-undefined', '-Wl,--build-id=none', '-Wl,-e,wave_output',
                    '-Wl,-T,' + str(folder / 'waves.ld'), '-I', str(HERE), str(HERE / 'waves.c'),
                    '-o', str(folder / 'waves.elf')], check=True, cwd=HERE, env=ZIG_ENV)
    elf = (folder / 'waves.elf').read_bytes()
    blob, symbols = v3.read_elf(elf, v3.LINK_BASE, v3.OS_POOL_END)
    symbols['wave_core'] = elf_symbol(elf, 'wave_core')
    (folder / 'waves.bin').write_bytes(blob)
    return blob, symbols


def elf_symbol(data, wanted):
    shoff = struct.unpack_from('<I', data, 32)[0]
    shsize, count, _ = struct.unpack_from('<3H', data, 46)
    sections = [struct.unpack_from('<10I', data, shoff + i * shsize) for i in range(count)]
    for name, kind, flags, addr, off, size, link, info, align, entsize in sections:
        if kind == 2:
            strings = sections[link]
            text = data[strings[4]:strings[4] + strings[5]]
            for at in range(off, off + size, entsize):
                n, value = struct.unpack_from('<2I', data, at)
                if text[n:].split(b'\0')[0] == wanted.encode():
                    return value
    raise ValueError(wanted + ' not found')


README = """DOOM/poly-v4 + 17 Wave Lab waves, RAM build v4 -- 2026-10-06
=============================================================

Built by the Claude audit session (waves_v4_ram/build_v4.py). Same layout as
v3-ram: all Sound Generator code runs from RAM, nothing from flash.

New in v4 (on top of v3-ram)
- DUTY knob crackle fix: a DUTY change of 1-2 steps must hold for 50 ms before
  it counts, so a flickering knob reading at rest is ignored. Real turns (3+
  steps) apply at once. Every change then glides over ~10 ms instead of
  jumping, so sweeping DUTY no longer zippers.
- Equal loudness: every new wave is matched to the same RMS at every DUTY
  setting (about 6 dB under full scale, close to the stock Saw), capped so its
  peak never clips. Very peaky shapes stay a little quieter rather than clip.
- DC removed per wave and DUTY (Drive sat ~37% off-centre in v3).
- Not changed: aliasing that is part of a wave's character (CZRes, Sync at
  mid DUTY, Vowel, high-DUTY CZ/Table, Logic/Metal/Grit), same as the browser.

Also kept: release-click fix, Noise1/2 label fix, four voices, chord REC,
stock waves unchanged.

Trade-off: OS memory pool {pool_kib:.1f} KB smaller than v4 ({pool_pct:.1f}% of stock).

Files (use BOTH, together):
  SP404MKII_APP1.bin  {app1_size:,} bytes  SHA-256 {app1_sha}
  SP404MKII_APP0.bin  {app0_size:,} bytes  SHA-256 {app0_sha}  (Roland stock)

Status: verified in emulation (waves_v4_ram/test_v4.py). NOT run on hardware.
Roll back with doom-poly-waves-v3-ram, doom-poly-v4-releasefix or Roland 5.52.

Quick test
1. FM1:1, hold a note, hands off: should be clean now.
2. Sweep DUTY slowly and fast on FM1:1, Fold, LPSaw, Vowel: smooth, no crackle.
3. Step TYPE through all 17 at LEVEL 127: similar loudness.
4. Drive: no thump at note start/stop.
"""


def main():
    v3.require((HERE / 'wave_tables.h').read_bytes(), TABLES_SHA, 'wave_tables.h')
    placeholder = [[(0.0, 1.0)] * 101 for _ in range(17)]
    write_level_header(placeholder)
    levels, report = measure(host_dll())
    level_sha = write_level_header(levels)
    print('wave duty   mean    rms   peak   gain   ->rms')
    for kind, duty, mean, rms, peak, gain, final in report:
        print(f'{kind:4} {duty:4} {mean:6.3f} {rms:6.3f} {peak:6.3f} {gain:6.2f} {final:6.3f}')
    module, symbols = compile_arm()
    base = v3.BASE.read_bytes()
    image, info = v3.build_image(base, module, {k: symbols[k] for k in ('wave_eval', 'wave_output', 'wave_name')})
    app0 = v3.APP0.read_bytes()
    v3.require(app0, v3.APP0_SHA, 'stock APP0')
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)
    (OUT / 'SP404MKII_APP1.bin').write_bytes(image)
    (OUT / 'SP404MKII_APP0.bin').write_bytes(app0)
    info['symbols'] = symbols
    info.update(revision='v4-ram', status='hardware-unverified', execution='sdram',
                base_sha256=v3.BASE_SHA, sha256=v3.sha(image), size=len(image),
                module_sha256=v3.sha(module), wave_level_sha256=level_sha,
                waves_c_sha256=v3.sha((HERE / 'waves.c').read_bytes()), tables_sha256=TABLES_SHA,
                duty={'hold_samples': 2400, 'immediate_steps': 3, 'glide_per_sample': 0.002},
                loudness={'target_rms': TARGET_RMS, 'peak_max': PEAK_MAX, 'gain_max': GAIN_MAX,
                          'reference_midi': REF_NOTES},
                types={str(i + 15): n for i, n in enumerate(v3.TYPES)})
    (OUT / 'manifest.json').write_text(json.dumps(info, indent=2, sort_keys=True) + '\n')
    shrink = info['pool_bytes_v4'] - info['pool_bytes']
    (OUT / 'README.txt').write_text(README.format(
        pool_kib=shrink / 1024, pool_pct=100 * info['pool_bytes'] / info['pool_bytes_stock'],
        app1_size=len(image), app1_sha=v3.sha(image), app0_size=len(app0), app0_sha=v3.sha(app0)),
        encoding='utf-8')
    print(f'{OUT}: APP1 {len(image)} bytes SHA-256 {v3.sha(image)}')
    print(f'module {len(module)} bytes; pool base {info["pool_base"]:#x}, {shrink} bytes less than v4')


if __name__ == '__main__':
    main()
