"""Build Sound Generator v9 (RAM, OS pool untouched): v8 + real envelopes,
filter envelopes and voice stealing.

- ENV keeps its ten values. OFF is stock. Roland's nine attack-only shapes
  (A..C2, at most one waveform cycle long) become nine timed presets: five
  volume envelopes and four that also sweep a resonant low-pass filter.
  They work on every wave, stock included, on all four voices and in REC export.
- Released notes ring out for the preset's release time. All-stop still cuts
  everything with the stock ~8 ms fade, long releases included.
- A fifth note no longer gets dropped: it takes the oldest fading voice, else
  the oldest held one; v9.5 fades it out in 2.8 ms before a fresh start. A 30 ms
  no-audio timeout uses the older in-place de-click fallback. The later note-off is
  ignored, so it cannot release another note.
Everything else is v8: the 17 waves with raw DUTY grit, loudness tables, quiet
Pulse/Noise, the OCT note-off fallback, the layout in unused SDRAM.
v9.1-v9.4 add: REC and TYPE-display fixes, the REC end fade, the FREQ readout
following the latest note, scale pads, MIDI IN on all four voices, and a fade
instead of a cut when REC starts with notes held (see README below).

Archived build helper; in this public repository use synth/build_v9.py.
Its wrapper supplies the official stock input, verified base and compiler.
"""
import hashlib
import json
import math
import re
import shutil
import struct
import subprocess
import sys
from pathlib import Path

import capstone

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT / 'waves_v7_ram'))
import build_v7 as v7b  # noqa: E402  (also sets up the v3-v6 pipeline modules)

v7b.v4b.HERE = v7b.v6b.HERE = HERE
v3, v4b, v5b, v6b, v4, v2 = v7b.v3, v7b.v4b, v7b.v5b, v7b.v6b, v7b.v4, v7b.v3.v2
load, call, jump = v3.load, v3.call, v3.jump
OUT = ROOT / 'firmware' / 'doom-poly-waves-v9.5-ram'   # v9.4 + click-free voice stealing
V8_MANIFEST = ROOT / 'firmware' / 'doom-poly-waves-v8-ram' / 'manifest.json'
STOCK = ROOT / 'firmware' / 'v552' / 'sp404mk2_sys_v552' / 'SP404MKII_APP1.bin'
CODE_BASE = v6b.CODE_BASE
ENV_NAME = CODE_BASE + 0x200          # bridge for the ENV value text
FREQ_TEXT = CODE_BASE + 0x240         # bridge: the FREQ readout shows the latest note's voice
FREQ_TEXT_SITE = 0x80131CC8           # FREQ case of the value-text function
FREQ_GET_SITE = 0x80020474            # FREQ case of the parameter getter
ENV_STAGE_SITE = 0x80007E50           # stock ENV step at the end of the oscillator
ENV_TEXT_SITE = 0x80131DF4            # ENV case of the value-text function
SR = 48000

# name, volume (attack, decay, sustain, release), filter or None:
# (octaves above the note, envelope depth in octaves, attack, decay, sustain,
#  release, damping k: 2 = no resonance, smaller = more, input drive, output gain).
# Times in seconds; decay and release are -60 dB times.
PRESETS = [
    ('OFF', None, None),
    ('Pluck', (0.002, 0.30, 0.00, 0.20), None),
    ('Perc', (0.002, 1.20, 0.00, 0.60), None),
    ('Keys', (0.005, 1.60, 0.45, 0.40), None),
    ('Pad', (0.350, 0.60, 1.00, 1.40), None),
    ('Swell', (1.600, 0.60, 1.00, 2.20), None),
    ('Bass', (0.002, 0.80, 0.65, 0.12), (0.8, 4.2, 0.002, 0.35, 0.00, 0.12, 1.10, 1.0, 1.15)),
    ('Acid', (0.002, 0.20, 0.90, 0.05), (0.4, 5.6, 0.002, 0.30, 0.00, 0.05, 0.22, 1.5, 0.85)),
    ('Sweep', (0.010, 0.50, 1.00, 0.80), (-0.8, 6.5, 2.800, 1.50, 1.00, 0.80, 0.55, 1.0, 1.10)),
    ('FPad', (0.450, 0.80, 1.00, 1.60), (0.3, 3.6, 1.400, 2.50, 0.45, 1.60, 0.90, 1.0, 1.15)),
]


def retain(seconds, scale):
    """Per-sample retention factor of a one-pole segment."""
    return math.exp(-1 / max(seconds / scale * SR, 1e-9))


def preset_rows():
    rows = []
    for name, amp, filt in PRESETS:
        if amp is None:
            rows.append((name, [1.0] * 8 + [0.0, 0.0, 2.0, 1.0, 1.0], 0))
            continue
        a, d, s, r = amp
        values = [retain(a, 1.466), retain(d, 6.908), s, retain(r, 6.908)]
        if filt:
            base, depth, fa, fd, fs, fr, k, drive, gain = filt
            values += [retain(fa, 1.466), retain(fd, 6.908), fs, retain(fr, 6.908), base, depth, k, drive, gain]
        else:
            values += [1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 2.0, 1.0, 1.0]
        rows.append((name, values, 1 if filt else 0))
    return rows


def cfloat(v):
    text = '%.9g' % v
    return (text if '.' in text or 'e' in text else text + '.0') + 'f'


def write_preset_header():
    lines = ['/* Generated by build_v9.py: ENV presets, 48 kHz retention factors. */',
             'typedef struct {',
             '    float ra, rd, sus, rr;              /* volume: attack, decay, sustain, release */',
             '    float fra, frd, fsus, frr;          /* filter envelope */',
             '    float base, amount, k, drive, gain; /* cutoff = note * 2^(base + amount*env) */',
             '    int filter;',
             '} preset_t;',
             'static const preset_t presets[10] = {']
    for name, values, filt in preset_rows():
        lines.append('    {' + ', '.join(cfloat(v) for v in values) + f', {filt}}},  /* {name} */')
    lines.append('};')
    names = ', '.join('"%s"' % name for name, _, _ in PRESETS)
    lines.append(f'static const char preset_names[10][6] = {{{names}}};')
    text = '\n'.join(lines) + '\n'
    (HERE / 'env_presets.h').write_text(text, encoding='ascii', newline='\n')
    return hashlib.sha256(text.encode('ascii')).hexdigest()


def read_module(data, link_base, limit):
    """Allocated sections (BSS as zeros, copied at boot) and every global symbol."""
    if data[:7] != b'\x7fELF\x01\x01\x01' or struct.unpack_from('<H', data, 18)[0] != 40:
        raise ValueError('expected little-endian ARM ELF32')
    shoff = struct.unpack_from('<I', data, 32)[0]
    shsize, count, _ = struct.unpack_from('<3H', data, 46)
    sections = [struct.unpack_from('<10I', data, shoff + i * shsize) for i in range(count)]
    syms, blocks, end = {}, [], link_base
    for name, kind, flags, addr, off, size, link, info, align, entsize in sections:
        if flags & 2 and size:
            if not link_base <= addr < limit or addr + size > limit:
                raise ValueError('unexpected allocated ELF address')
            blocks.append((addr, bytes(size) if kind == 8 else data[off:off + size]))
            end = max(end, addr + size)
        if kind == 2:
            strings = sections[link]
            text = data[strings[4]:strings[4] + strings[5]]
            for at in range(off, off + size, entsize):
                n, value, _, sym_info = struct.unpack_from('<3IB', data, at)
                label = text[n:].split(b'\0')[0].decode('ascii')
                if sym_info >> 4 == 1 and label:          # global
                    syms[label] = value
    out = bytearray(end - link_base)
    for addr, block in blocks:
        out[addr - link_base:addr - link_base + len(block)] = block
    return bytes(out), syms


LINKER = v3.LINKER.replace('KEEP(*(.text.wave_name))',
                           'KEEP(*(.text.wave_name)) KEEP(*(.text.env_stage)) KEEP(*(.text.env_name)) '
                           'KEEP(*(.text.note_event)) KEEP(*(.text.export_mix)) KEEP(*(.text.freq_get)) '
                           'KEEP(*(.text.freq_event)) KEEP(*(.text.display_voice)) KEEP(*(.text.midi_event)) '
                           'KEEP(*(.text.kb_pad_note)) KEEP(*(.text.kb_in_scale)) KEEP(*(.text.kb_pad_rel))')


def compile_arm():
    folder = HERE / 'build' / 'ram'
    folder.mkdir(parents=True, exist_ok=True)
    if LINKER == v3.LINKER:
        raise ValueError('v3 linker script changed')
    (folder / 'waves.ld').write_text(LINKER.format(base=v6b.LINK_BASE), encoding='ascii', newline='\n')
    subprocess.run([str(v3.ZIG), 'cc', '-target', 'thumb-freestanding-eabihf',
                    '-mcpu=cortex_m7+vfp4d16', '-mfpu=vfpv4-d16', '-mfloat-abi=hard', *v4b.COMMON,
                    '-nostdlib', '-Wl,--no-undefined', '-Wl,--build-id=none', '-Wl,-e,wave_output',
                    '-Wl,-T,' + str(folder / 'waves.ld'), '-I', str(HERE), '-I', str(ROOT / 'waves_v8_ram'), str(ROOT / 'waves_v8_ram' / 'waves.c'),
                    str(HERE / 'env.c'), '-o', str(folder / 'waves.elf')],
                   check=True, cwd=HERE, env=v4b.ZIG_ENV)
    elf = (folder / 'waves.elf').read_bytes()
    blob, symbols = read_module(elf, v6b.LINK_BASE, v6b.NONCACHE)
    needed = {'wave_output', 'wave_name', 'wave_eval', 'wave_core', 'env_stage', 'env_name',
              'note_event', 'export_mix', 'freq_get', 'freq_event', 'display_voice', 'display_slot',
              'midi_event', 'kb_pad_note', 'kb_in_scale', 'kb_pad_rel',
              'env_fast', 'env_quick', 'env_slot', 'env_restart', 'env_age', 'stolen_valid'}
    if not needed <= set(symbols):
        raise ValueError(f'module exports missing: {sorted(needed - set(symbols))}')
    (folder / 'waves.bin').write_bytes(blob)
    return blob, {k: symbols[k] for k in sorted(needed)}


SOUNDING, SELECTED = 'ldrb.w r0, [r0, #0x70]', 'ldrb.w r0, [r0, #0x71]'

# Stock UI code that read the sounding TYPE (+0x70). The oscillator only swaps
# it in after a ~4 ms crossfade, and never while a voice fades out, so the TYPE
# knob stepped from a stale value and the screen lagged. They read the selected
# TYPE (+0x71) instead; audio code keeps reading the sounding one.
UI_TYPE_READS = [
    (0x80019FA0, 'r0', 'r4'),   # setter: TYPE unchanged? / DUTY default when leaving noise
    (0x80019FC0, 'r0', 'r4'),   # setter: is DUTY used by this TYPE
    (0x8002046C, 'r0', 'r0'),   # getter: TYPE (the knob steps from it)
    (0x80020474, 'r1', 'r0'),   # getter: FREQ
    (0x800204A4, 'r1', 'r0'),   # getter: DUTY
    (0x80131BA4, 'r0', 'r0'),   # label: DUTY
    (0x80131CC8, 'r2', 'r0'),   # value text: FREQ
    (0x80131D98, 'r1', 'r0'),   # value text: DUTY
    (0x801326A0, 'r0', 'r0'),   # range: FREQ
    (0x801326BC, 'r0', 'r0'),   # range: DUTY
    (0x8015C5F8, 'r1', 'r0'),   # START/END allowed
    (0x8002B94C, 'r2', 'r0'),   # START/END allowed (page 66)
]


def gate_sources(symbols):
    """v7's gates reading the selected TYPE; FREQ_LABEL's slot ends at the ENV name bridge."""
    osc, name, freq = v7b.gate_sources(symbols)
    if not name[2].strip().startswith(SOUNDING) or not freq[2].strip().startswith(SOUNDING):
        raise ValueError('v6 name/label gate source changed')
    name = (name[0], name[1], name[2].replace(SOUNDING, SELECTED, 1))
    freq = (freq[0], ENV_NAME, freq[2].replace(SOUNDING, SELECTED, 1))
    return [osc, name, freq,
            (ENV_NAME, ENV_NAME + 0x40, f'''
                ldr r0, [r0, #0x10]
                mov r1, r4
                {call(symbols['env_name'])}
                {jump(0x80131C78)}
            '''),
            (FREQ_TEXT, FREQ_TEXT + 0x40, f'''
                ldrb.w r2, [r0, #0x71]
                cmp r2, #31
                bhi no_note
                push {{r1, r2}}
                {call(symbols['display_voice'])}
                pop {{r1, r2}}
                {jump(0x80131CD2)}
            no_note:
                {jump(0x80131E20)}
            ''')]


v6b.gate_sources = gate_sources


def stock_bytes(address, size):
    stock = STOCK.read_bytes()
    return stock[v2.old_high_file(address):v2.old_high_file(address) + size]


def replace(image, address, expected, replacement):
    off = v3.file_offset(image, address, len(expected))
    if image[off:off + len(expected)] != expected:
        raise ValueError(f'unexpected bytes at {address:#x}')
    if len(replacement) > len(expected):
        raise ValueError(f'patch at {address:#x} is too long')
    out = bytearray(image)
    out[off:off + len(expected)] = replacement.ljust(len(expected), b'\0')
    return bytes(out)


def release_sources(symbols):
    """(release-fixed all-stop engine as in the base image, v9 version marking env_fast)."""
    fixed = v4.release_source().replace('        str r0, [r4, #0x4c]\n',
                                        '        mvn r0, #0xc7\n        str r0, [r4, #0x4c]\n')
    head = 'push {r4-r6, lr}\n'
    if fixed.count('str r0, [r4, #0x4c]') != 1 or head not in fixed:
        raise ValueError('v4 release source changed')
    marks = (load('r0', symbols['env_fast']) + 'movs r1, #1\n' +
             ''.join(f'strb r1, [r0, #{i}]\n' for i in range(4)))
    return fixed, fixed.replace(head, head + marks, 1)


def check_stage_entry(image):
    """Nothing may branch into the bytes the ENV stage call replaces, except its start."""
    md = capstone.Cs(capstone.CS_ARCH_ARM, capstone.CS_MODE_THUMB | capstone.CS_MODE_MCLASS)
    lo, hi = 0x80007700, ENV_STAGE_SITE
    off = v3.file_offset(image, lo, hi - lo)
    for ins in md.disasm(image[off:off + (hi - lo)], lo):
        if ins.mnemonic.startswith(('b', 'cb')) and ins.op_str.startswith('#'):
            target = int(ins.op_str.split('#')[-1], 16)
            if ENV_STAGE_SITE < target < ENV_STAGE_SITE + 0x14:
                raise ValueError(f'branch into the ENV stage call at {ins.address:#x}')


def build_image(module, symbols, base=None):
    if base is None:
        base = v3.BASE.read_bytes()
    image, info = v6b.build_image(base, module, symbols)
    image = v5b.apply_extra(image)
    size = v4.PARAM_ENGINE - v4.NOTE_ENGINE
    old_note = v3.asm(v7b.note_sources()[0], v4.NOTE_ENGINE).ljust(size, b'\0')
    image = replace(image, v4.NOTE_ENGINE, old_note, v3.asm(jump(symbols['note_event']), v4.NOTE_ENGINE))
    size = v4.CAPTURE_INIT - v4.RELEASE_ENGINE
    old_release, new_release = release_sources(symbols)
    image = replace(image, v4.RELEASE_ENGINE, v3.asm(old_release, v4.RELEASE_ENGINE).ljust(size, b'\0'),
                    v3.asm(new_release, v4.RELEASE_ENGINE))
    check_stage_entry(image)
    stage = v3.asm(f'''
        mov r0, r4
        mov r1, r5
        {call(symbols['env_stage'])}
        vpop {{d8-d12}}
        pop {{r4-r6, pc}}
    ''', ENV_STAGE_SITE)
    image = replace(image, ENV_STAGE_SITE, stock_bytes(ENV_STAGE_SITE, len(stage)), stage)
    text = v3.asm(jump(ENV_NAME) + 'nop\n', ENV_TEXT_SITE)
    image = replace(image, ENV_TEXT_SITE, stock_bytes(ENV_TEXT_SITE, len(text)), text)
    v9_hooks = [[v4.NOTE_ENGINE, len(old_note)], [v4.RELEASE_ENGINE, size],
                [ENV_STAGE_SITE, len(stage)], [ENV_TEXT_SITE, len(text)]]
    for address, rt, rn in UI_TYPE_READS:
        old = v3.asm(f'ldrb.w {rt}, [{rn}, #0x70]', address)
        if stock_bytes(address, len(old)) != old:
            raise ValueError(f'stock TYPE read changed at {address:#x}')
        image = replace(image, address, old, v3.asm(f'ldrb.w {rt}, [{rn}, #0x71]', address))
        v9_hooks.append([address, len(old)])
    # REC: the chord snapshot takes the selected TYPE, not voice 0's sounding one.
    export = v4.export_source()
    chosen = export.replace('ldrb.w r0, [r4, #0x70]', 'ldrb.w r0, [r4, #0x71]', 1)
    old_export, new_export = v3.asm(export, v4.EXPORT_ENGINE), v3.asm(chosen, v4.EXPORT_ENGINE)
    if chosen == export or len(old_export) != len(new_export):
        raise ValueError('v4 export source changed')
    image = replace(image, v4.EXPORT_ENGINE, old_export, new_export)
    v9_hooks.append([v4.EXPORT_ENGINE, len(old_export)])
    # REC mixer -> export_mix (same mix, plus the one-shot end fade). Entered by a
    # jump from the oscillator gate, so sp and r10/r11 are still the exporter's.
    size = v4.OSC_GATE - v4.EXPORT_SAMPLE
    old_mix = v3.asm(v4.sample_source(), v4.EXPORT_SAMPLE).ljust(size, b'\0')
    mix = v3.asm('ldr r2, [sp, #4]\nmov r0, r10\nmov r1, r11\n' + jump(symbols['export_mix']),
                 v4.EXPORT_SAMPLE)
    image = replace(image, v4.EXPORT_SAMPLE, old_mix, mix)
    v9_hooks.append([v4.EXPORT_SAMPLE, size])
    # FREQ follows the latest note: getter case, readout text, and the knob's transpose.
    get_old = (v3.asm('ldrb.w r1, [r0, #0x71]\ncmp r1, #0x1f', FREQ_GET_SITE) +
               stock_bytes(FREQ_GET_SITE + 6, 6))           # bhi 0x800204b4; ldr r0, [r0, #0x5c]; bx lr
    image = replace(image, FREQ_GET_SITE, get_old, v3.asm(jump(symbols['freq_get']) + 'nop\n', FREQ_GET_SITE))
    text_old = (v3.asm('ldrb.w r2, [r0, #0x71]\ncmp r2, #31', FREQ_TEXT_SITE) +
                stock_bytes(FREQ_TEXT_SITE + 6, 4))         # bhi.w 0x80131e20
    image = replace(image, FREQ_TEXT_SITE, text_old, v3.asm(jump(FREQ_TEXT), FREQ_TEXT_SITE))
    size = v4.TUNE_RESET - v4.FREQ_ENGINE
    old_freq = v3.asm(v4.freq_source(), v4.FREQ_ENGINE).ljust(size, b'\0')
    image = replace(image, v4.FREQ_ENGINE, old_freq, v3.asm(jump(symbols['freq_event']), v4.FREQ_ENGINE))
    v9_hooks += [[FREQ_GET_SITE, len(get_old)], [FREQ_TEXT_SITE, len(text_old)], [v4.FREQ_ENGINE, size]]

    def stock_span(address, end, source):
        nonlocal image
        new = v3.asm(source, address)
        if len(new) > end - address or (end - address - len(new)) % 2:
            raise ValueError(f'patch at {address:#x} does not fit')
        # Keystone mis-encodes some absolute branches (beq.w #0x8015bfa6 came out as
        # beq.w #0x800b8036): every direct branch must hit a target named in the source.
        named = {int(t, 16) for t in re.findall(r'#(0x[0-9a-fA-F]+)', source)}
        md = capstone.Cs(capstone.CS_ARCH_ARM, capstone.CS_MODE_THUMB | capstone.CS_MODE_MCLASS)
        for ins in md.disasm(new, address):
            if ins.mnemonic.startswith(('b', 'cb')) and ins.op_str.split(', ')[-1].startswith('#'):
                target = int(ins.op_str.split('#')[-1], 16)
                if target not in named and not address <= target < address + len(new):
                    raise ValueError(f'patch at {address:#x}: branch at {ins.address:#x} to {target:#x}')
        image = replace(image, address, stock_bytes(address, end - address),
                        new + b'\0\xbf' * ((end - address - len(new)) // 2))
        v9_hooks.append([address, end - address])

    # Scale pads: the pad helpers used by the pad lights, and the SG page's own
    # note-on/note-off pad maths, all take kb_pad_note's note.
    for address, symbol in ((0x80030C88, 'kb_pad_note'), (0x80030FA8, 'kb_in_scale'),
                            (0x80030E98, 'kb_pad_rel')):
        stock_span(address, address + 12, jump(symbols[symbol]) + 'nop\n')
    stock_span(0x8015C070, 0x8015C0C8,           # note-on; off the SG page, stock's out-of-scale skip
               'mov r0, r4\n' + call(symbols['kb_pad_note']) + 'mov r6, r0\nmov r0, r4\n' +
               call(symbols['kb_in_scale']) + 'cmp r0, #0\nbeq #0x8015bfa6\nb #0x8015c0c8\n')
    stock_span(0x8015C4D0, 0x8015C4F0,           # note-off: same note, then the v2 dispatcher call
               'mov r0, r4\n' + call(symbols['kb_pad_note']) +
               'mov r1, r0\nmovs r2, #0\nmovs r3, #1\nstr r4, [sp]\n')
    # MIDI IN: the dispatcher's voice-0 call goes to the four-voice MIDI engine.
    stock_span(0x8005A694, 0x8005A6A4, 'uxtb r2, r5\nmov r3, r6\n' + call(symbols['midi_event']) + 'nop\n')
    # REC with notes held: fade the voices (all-stop) instead of cutting them.
    old_init, new_init = v4.capture_init_source(), v4.capture_init_source().replace(
        v4.call(v2.INIT_ALL_WRAPPER), v4.call(v4.RELEASE_ENGINE))
    if old_init == new_init:
        raise ValueError('v4 capture/init source changed')
    size = v4.LED_MATCH - v4.CAPTURE_INIT
    image = replace(image, v4.CAPTURE_INIT, v3.asm(old_init, v4.CAPTURE_INIT).ljust(size, b'\0'),
                    v3.asm(new_init, v4.CAPTURE_INIT))
    v9_hooks.append([v4.CAPTURE_INIT, size])
    info['hooks'] += [[a, len(v3.asm(b, a))] for a, b, _ in v5b.EXTRA] + v9_hooks
    info['v9_hooks'] = v9_hooks
    return image, info


README = """DOOM/poly-v4 + 17 Wave Lab waves, v9.5 (RAM, no memory taken) -- 2026-10-07
============================================================================

Built by the Claude session (waves_v9_ram/build_v9.py). v9.5 = v9.4 plus one fix
from your v9.4 hardware test:

- No click when a note takes a busy voice (all four sounding, e.g. letting go
  of one note of a chord and playing another while it still rings out). The
  voice used to be cut short in place: the old note stopped dead and its last
  sample decayed as a thump under the new note. Now the old note fades out in
  2.8 ms (the stock release fade, three times faster) and the new note starts
  cleanly on the free voice, about 3 ms later. Stock does the same kind of wait
  when you retrigger a releasing note. MIDI IN steals the same way.

v9.4 = v9.3 plus:

- Scale pads. With a SCALE other than Chrom, the 16 pads walk the scale
  instead of the semitones: no dark out-of-scale pads, and one bank covers
  two octaves and a step (7-note scales) or three full octaves (pentatonic).
  Pad 9 plays the first scale note at or above the note it played before,
  and the pads keep their order (bottom row lowest, top row highest, left to
  right), each one scale step above the one before. The pad lights keep
  their stock meaning (root pads, below / above the root). NOTE, OCT and the
  shift setting work as before. Chrom, and every other screen that shares
  the keyboard settings, are unchanged.
- MIDI IN plays all four voices (it was voice 0 only), with the same voice
  stealing as the pads. A held MIDI note lights the pad with the same pitch.
- Pressing REC while holding notes fades them out (~8 ms) instead of cutting
  them, so no click.
- Recording fade: every recording with an ENV preset fades out at the end.
  ENV OFF with Pad Length in periods and START/END on still ends on a whole
  cycle, so raw-wave loops stay seamless (v9.3 skipped the fade there even
  with a preset).

v9.3 = v9.2 plus:

- The FREQ readout follows the note you just played. It used to show voice
  0's note only, and with long releases voice 0 is often still fading, so
  new notes went to the other voices and the readout stayed on the old note.
- The FREQ knob steps from the note on the screen and moves every held note
  by the same amount, as before. If the note on the screen is fading out, the
  readout moves to the newest held note, so it always shows a note that moved.
- Pitch was measured and is exact (0.00 cents on every voice); only the
  readout was wrong.

v9.2 = your hardware-tested v9.1 plus one fix:

- No click at the end of a recorded pad. REC renders a fixed length (Pad
  Length) and used to stop wherever the sound was, so anything still sounding
  (Pad, Swell, Keys, the filter presets, and ENV OFF too) ended with a hard
  cut. Recordings now fade out over their last 10 ms (the last quarter on very
  short pads). The exception is a whole-cycle loop, Pad Length in periods with
  START/END on: the exporter trims those to whole cycles so they loop
  seamlessly, and they stay exactly as before.

v9.1 = v9 plus three fixes from your v9 hardware test:

- REC records the envelope again. v9 gave a blank pad: the stock exporter marks
  its own voice inactive while it renders it, and v9's envelope took that as
  "the note is over" and stayed silent.
- The TYPE knob and the screen follow your selection immediately. They read
  the type that was sounding, which lags by a ~4 ms crossfade and does not
  change at all while voice 0 is fading out, so the knob could stick and the
  name could freeze while the held notes changed.
- New notes, stolen voices and REC always use the selected TYPE.

What v9 added to v8:

- ENV is a real envelope now. OFF is unchanged. Roland's A..C2 (a fade-in
  lasting at most one waveform cycle, so they all sounded the same) are
  replaced by nine presets that work on every wave, stock ones included:
    Pluck  Perc  Keys  Pad  Swell        volume only
    Bass   Acid  Sweep FPad              plus a resonant low-pass that sweeps
  Released notes ring out for the preset's release time.
- All-stop (leaving the page, SUB PAD preview off, etc.) still cuts every voice
  within ~8 ms, long releases included.
- A fifth note is no longer dropped. It takes the oldest fading voice, or if
  none is fading, the oldest held one, with a 2 ms crossfade. Letting go of the
  stolen note's pad later does nothing.

Kept from v8: the 17 waves with raw DUTY grit, loudness/DC tables, Pulse and
Noise1/2 -6 dB, the OCT stuck-note fix, FREQ/ENV/START-END on new waves, the
release-click fix, and the wave code in unused SDRAM with the OS pool as in v4.

Files (use BOTH, together):
  SP404MKII_APP1.bin  {app1_size:,} bytes  SHA-256 {app1_sha}
  SP404MKII_APP0.bin  {app0_size:,} bytes  SHA-256 {app0_sha}  (Roland stock)

Status: verified in emulation (waves_v9_ram/test_v9.py), including REC through
the real stock exporter. v9.1 passed your hardware test; v9.5 is NOT run on
hardware yet. Roll back with doom-poly-waves-v9.4-ram or v9.1-ram.
"""


def main():
    v3.require((HERE / 'wave_tables.h').read_bytes(), v4b.TABLES_SHA, 'wave_tables.h')
    v8 = json.loads(V8_MANIFEST.read_text())
    level = (HERE / 'wave_level.h').read_bytes()
    v3.require(level, v8['wave_level_sha256'], "v8's wave_level.h")
    preset_sha = write_preset_header()
    module, symbols = compile_arm()
    image, info = build_image(module, symbols)
    app0 = v3.APP0.read_bytes()
    v3.require(app0, v3.APP0_SHA, 'stock APP0')
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)
    (OUT / 'SP404MKII_APP1.bin').write_bytes(image)
    (OUT / 'SP404MKII_APP0.bin').write_bytes(app0)
    info.update(revision='v9.5-ram', status='hardware-unverified', execution='sdram-gap',
                symbols=symbols, base_sha256=v3.BASE_SHA, sha256=v3.sha(image), size=len(image),
                module_sha256=v3.sha(module), wave_level_sha256=v8['wave_level_sha256'],
                waves_c_sha256=v3.sha((HERE / 'waves.c').read_bytes()),
                env_c_sha256=v3.sha((HERE / 'env.c').read_bytes()), env_presets_sha256=preset_sha,
                tables_sha256=v4b.TABLES_SHA, extra_fixes=[[hex(a), b, c] for a, b, c in v5b.EXTRA],
                duty='raw (stock integer DUTY, no smoothing)', polyblep=[],
                quiet_stock_types={'11': 'Pulse', '13': 'Noise1', '14': 'Noise2'}, quiet_gain_db=-6.02,
                env_presets={name: {'volume': amp, 'filter': filt} for name, amp, filt in PRESETS},
                stealing='oldest fading voice, else oldest held; 2.8 ms fade-out then fresh start; 30 ms no-audio timeout uses in-place declick; stolen note-offs ignored',
                note_off='stolen notes ignored; exact note+source; else one non-releasing voice of that source',
                sdram_gap=['0x83f7a424', '0x83ff0000'],
                types={str(i + 15): n for i, n in enumerate(v3.TYPES)})
    (OUT / 'manifest.json').write_text(json.dumps(info, indent=2, sort_keys=True) + '\n')
    (OUT / 'README.txt').write_text(README.format(
        app1_size=len(image), app1_sha=v3.sha(image), app0_size=len(app0), app0_sha=v3.sha(app0)),
        encoding='utf-8')
    print(f'{OUT}: APP1 {len(image)} bytes SHA-256 {v3.sha(image)}')
    print(f'module {len(module)} bytes; env_stage {symbols["env_stage"]:#x} note_event {symbols["note_event"]:#x}')


if __name__ == '__main__':
    main()
