/* Generated by build_v9.py: ENV presets, 48 kHz retention factors. */
typedef struct {
    float ra, rd, sus, rr;              /* volume: attack, decay, sustain, release */
    float fra, frd, fsus, frr;          /* filter envelope */
    float base, amount, k, drive, gain; /* cutoff = note * 2^(base + amount*env) */
    int filter;
} preset_t;
static const preset_t presets[10] = {
    {1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 2.0f, 1.0f, 1.0f, 0},  /* OFF */
    {0.984845175f, 0.999520393f, 0.0f, 0.999280676f, 1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f, 2.0f, 1.0f, 1.0f, 0},  /* Pluck */
    {0.984845175f, 0.999880077f, 0.0f, 0.999760168f, 1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f, 2.0f, 1.0f, 1.0f, 0},  /* Perc */
    {0.993910285f, 0.999910056f, 0.45f, 0.999640273f, 1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f, 2.0f, 1.0f, 1.0f, 0},  /* Keys */
    {0.999912742f, 0.999760168f, 1.0f, 0.999897208f, 1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f, 2.0f, 1.0f, 1.0f, 0},  /* Pad */
    {0.999980912f, 0.999760168f, 1.0f, 0.999934585f, 1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f, 2.0f, 1.0f, 1.0f, 0},  /* Swell */
    {0.984845175f, 0.99982012f, 0.65f, 0.998801413f, 0.984845175f, 0.999588894f, 0.0f, 0.998801413f, 0.8f, 4.2f, 1.1f, 1.0f, 1.15f, 1},  /* Bass */
    {0.984845175f, 0.999280676f, 0.9f, 0.997125805f, 0.984845175f, 0.999520393f, 0.0f, 0.997125805f, 0.4f, 5.6f, 0.22f, 1.5f, 0.85f, 1},  /* Acid */
    {0.996950493f, 0.999712208f, 1.0f, 0.99982012f, 0.999989092f, 0.99990406f, 1.0f, 0.99982012f, -0.8f, 6.5f, 0.55f, 1.0f, 1.1f, 1},  /* Sweep */
    {0.999932132f, 0.99982012f, 1.0f, 0.999910056f, 0.999978185f, 0.999942435f, 0.45f, 0.999910056f, 0.3f, 3.6f, 0.9f, 1.0f, 1.15f, 1},  /* FPad */
};
static const char preset_names[10][6] = {"OFF", "Pluck", "Perc", "Keys", "Pad", "Swell", "Bass", "Acid", "Sweep", "FPad"};
