"""Reproduce the exact Wave Lab v8 RAM image and our browser overlay.

Requires owner's stock 5.52 APP1/APP0 and Zig 0.13.0. Never flashes a device.
Uses the frozen v8 loudness/DC table; no smoother or PolyBLEP is added.
"""
import argparse
import base64
import importlib.util
import json
import os
from pathlib import Path
import subprocess
import sys

import build
import patch_release

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
V8 = HERE / 'ram' / 'waves_v8_ram'
EXPECTED_SHA = '12dbeae4c85722e3109aa2359102e8525c0c5e3729fb64126456abd83ae283c7'
EXPECTED_SIZE = 2961072
BASE_SHA = '5ef3642a238d157f0176547dc22d11d46f445072e3aa0ae47879ac304e42cae3'
SOURCE_LF_HASHES = {
    'waves.c':'1e17121b5c0036c55603533f30a97d9391ac63e890e5e92c91af67b04eba8b93',
    'wave_tables.h':'f76cfd8610416574333499472bad6e9e51a492bd446396a1ba2c5d45c4db75b6',
    'wave_level.h':'1815a05a2d8013785db22047dd838ab4c082d1f4e573fec6418d63b4e3cf8bd5',
}


def verified_sources():
    info = json.loads((V8 / 'manifest.json').read_text(encoding='utf-8'))
    provenance = {}
    for name, field in (('waves.c', 'waves_c_sha256'),
                        ('wave_tables.h', 'tables_sha256'),
                        ('wave_level.h', 'wave_level_sha256')):
        # Original C/table files used CRLF. Git publication uses normalized LF;
        # content is identical, and compiled module/final image hashes stay exact.
        data = (V8 / name).read_bytes().replace(b'\r\n', b'\n')
        build.require_hash(data, SOURCE_LF_HASHES[name], name+' (LF)')
        provenance[name] = info[field]
        info[field] = SOURCE_LF_HASHES[name]
    info['original_build_source_sha256'] = provenance
    info['source_line_endings'] = 'Hashes of public sources use normalized LF'
    if info['sha256'] != EXPECTED_SHA or info['size'] != EXPECTED_SIZE:
        raise ValueError('unexpected v8 reference manifest')
    return info


def compile_and_build(stock, zig):
    info = verified_sources()
    if subprocess.check_output([str(zig), 'version'], text=True).strip() != '0.13.0':
        raise ValueError('exact reproduction requires Zig 0.13.0')
    spec = importlib.util.spec_from_file_location('_waves_v8_ram_build', V8 / 'build_v8.py')
    ram = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(ram)
    ram.v3.ZIG = zig
    cache = REPO / 'build' / 'v8-cache'
    ram.v4b.ZIG_ENV = dict(os.environ, ZIG_GLOBAL_CACHE_DIR=str(cache),
                          ZIG_LOCAL_CACHE_DIR=str(cache))
    _, base = build.build(stock)
    build.require_hash(base, BASE_SHA, 'DOOM/poly-v4')
    released = patch_release.patch(base)
    build.require_hash(released, info['base_sha256'], 'release-fixed base')
    module, symbols = ram.compile_arm()
    build.require_hash(module, info['module_sha256'], 'v8 compiled module')
    if symbols != info['symbols']:
        raise ValueError('v8 symbol addresses differ from reference')
    image, layout = ram.v6b.build_image(released, module, symbols)
    image = ram.v5b.apply_extra(image)
    image, note_size = ram.v7b.patch_note_engine(image)
    build.require_hash(image, EXPECTED_SHA, 'v8 APP1')
    if len(image) != EXPECTED_SIZE or note_size != info['note_engine_bytes']:
        raise ValueError('v8 size/note engine differs from reference')
    for key in ('code_base', 'code_file', 'code_size', 'pool_base'):
        if layout[key] != info[key]:
            raise ValueError('v8 layout differs from reference: '+key)
    info.update(source_sha256=BASE_SHA, release_fix=True, noise_freq_label_fix=True,
                experimental=True, tests='Emulator-tested; hardware-unverified')
    return base, image, info


def publish_overlay(base, image, info):
    build.require_hash(base, BASE_SHA, 'browser overlay base')
    build.require_hash(image, EXPECTED_SHA, 'browser overlay v8 target')
    if len(image) != EXPECTED_SIZE:
        raise ValueError('unexpected v8 browser output size')
    overlay = build.make_overlay(base, image, '5.52+waves-v8')
    # Round trip verified by make_overlay; no complete firmware is published.
    text = '// Generated by synth/build_v8.py --web; v8-ram, hardware-unverified.\n'
    text += 'window.DOOMOS_WAVES = '+json.dumps(info, sort_keys=True)+';\n'
    text += 'window.DOOMOS_WAVES_PATCH = '+json.dumps(base64.b64encode(overlay).decode('ascii'))+';\n'
    (REPO / 'waves-data.js').write_text(text, encoding='ascii', newline='\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('stock', type=Path)
    parser.add_argument('--zig', type=Path, required=True)
    parser.add_argument('--out', type=Path, default=REPO / 'out' / 'doom-poly-waves-v8-ram')
    parser.add_argument('--web', action='store_true')
    args = parser.parse_args()
    if args.out.exists():
        raise ValueError('refusing to overwrite existing output; choose a fresh --out directory')
    app0 = args.stock.with_name('SP404MKII_APP0.bin').read_bytes()
    build.require_hash(app0, build.APP0_SHA, 'stock APP0')
    base, image, info = compile_and_build(args.stock.read_bytes(), args.zig.resolve())
    args.out.mkdir(parents=True)
    (args.out / 'SP404MKII_APP1.bin').write_bytes(image)
    (args.out / 'SP404MKII_APP0.bin').write_bytes(app0)
    (args.out / 'manifest.json').write_text(json.dumps(info, indent=2, sort_keys=True)+'\n')
    if args.web:
        publish_overlay(base, image, info)
    print(f'v8 APP1: {len(image)} bytes; SHA-256 {build.sha(image)}')
    print('APP0 unchanged; emulator-tested, hardware-unverified; no flashing performed.')


if __name__ == '__main__':
    main()
