"""Reproduce/publish exact v9.1 Sound Generator; no full firmware is published.

Uses the frozen v8 waveform/level tables plus archived v9 envelope sources.
--candidate publishes an existing hash-pinned owner image without rebuilding.
Otherwise requires Zig 0.13.0. Never loads a host DLL or flashes a device.
"""
import argparse
import base64
import importlib.util
import json
import os
from pathlib import Path
import subprocess

import build
import build_v8
import patch_release

HERE = Path(__file__).resolve().parent
RAM = HERE / 'ram' / 'waves_v9_ram'
EXPECTED_SHA = 'dad6f0d4baa3d26a613b86dc92e7ab1d3765c10e8a532e2dd3eefdf5093a1c33'
EXPECTED_SIZE = 2966032
SOURCE_HASHES = {
    'env.c': '0e7645bd084d2bb9e82bbeeda095457eaadb4b369bb894912316ea9bf38dc582',
    'env_presets.h': '7cecb79550c7a69b182768401c9ef2a8c10b114c2b9147d5dfb8f790ea86b2d9',
}


def verified_sources():
    build_v8.verified_sources()  # Same frozen waveform and loudness/DC tables.
    for name, digest in SOURCE_HASHES.items():
        build.require_hash((RAM/name).read_bytes().replace(b'\r\n', b'\n'), digest, name)
    info = json.loads((RAM/'manifest.json').read_text())
    if info['sha256'] != EXPECTED_SHA or info['size'] != EXPECTED_SIZE:
        raise ValueError('unsupported v9.1 reference manifest')
    info.update(source_sha256=build_v8.BASE_SHA, release_fix=True,
        noise_freq_label_fix=True, experimental=True,
        status='owner-reported-hardware-working',
        hardware_validation={'source': 'owner report', 'date': '2026-10-07',
            'detail': 'hardware test is good', 'coverage': 'unspecified',
            'cpu_headroom': 'unmeasured'},
        tests='24 v9.1 emulator checks; 10 byte-exact stereo/mono export cases; 8 oracle tests')
    info['source_line_endings'] = 'Public waveform sources normalized LF, compiled bytes unchanged'
    info['original_build_source_sha256'] = {key: info[key] for key in ('waves_c_sha256', 'tables_sha256')}
    info['waves_c_sha256'] = build_v8.SOURCE_LF_HASHES['waves.c']
    info['tables_sha256'] = build_v8.SOURCE_LF_HASHES['wave_tables.h']
    return info


def compile_and_build(stock_path, zig):
    info = verified_sources()
    if subprocess.check_output([str(zig), 'version'], text=True).strip() != '0.13.0':
        raise ValueError('exact reproduction requires Zig 0.13.0')
    spec = importlib.util.spec_from_file_location('_waves_v9_ram_build', RAM/'build_v9.py')
    ram = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(ram)
    ram.v3.ZIG = zig
    ram.STOCK = stock_path
    cache = build.REPO/'build'/'v9-cache'
    ram.v4b.ZIG_ENV = dict(os.environ, ZIG_GLOBAL_CACHE_DIR=str(cache), ZIG_LOCAL_CACHE_DIR=str(cache))
    _, base = build.build(stock_path.read_bytes())
    build.require_hash(base, build_v8.BASE_SHA, 'DOOM/poly-v4')
    released = patch_release.patch(base)
    build.require_hash(released, info['base_sha256'], 'release-fixed base')
    ram.write_preset_header()
    module, symbols = ram.compile_arm()
    build.require_hash(module, info['module_sha256'], 'v9.1 compiled module')
    if symbols != info['symbols']:
        raise ValueError('v9.1 compiled symbols differ')
    image, layout = ram.build_image(module, symbols, base=released)
    build.require_hash(image, EXPECTED_SHA, 'v9.1 rebuilt APP1')
    if len(image) != EXPECTED_SIZE:
        raise ValueError('v9.1 rebuilt size differs')
    for key in ('code_base', 'code_file', 'code_size', 'pool_base', 'v9_hooks'):
        if layout[key] != info[key]:
            raise ValueError('v9.1 layout differs: '+key)
    return base, image, info


def publish_overlay(base, image, info):
    build.require_hash(base, build_v8.BASE_SHA, 'browser base')
    build.require_hash(image, EXPECTED_SHA, 'browser v9.1 target')
    if len(image) != EXPECTED_SIZE or info['size'] != EXPECTED_SIZE or info['sha256'] != EXPECTED_SHA or info['revision'] != 'v9.1-ram':
        raise ValueError('invalid browser metadata')
    overlay = build.make_overlay(base, image, '5.52+waves-v9.1')
    text = '// Generated by synth/build_v9.py --web; v9.1-ram, owner-reported hardware working.\n'
    text += 'window.DOOMOS_WAVES = '+json.dumps(info, sort_keys=True)+';\n'
    text += 'window.DOOMOS_WAVES_PATCH = '+json.dumps(base64.b64encode(overlay).decode('ascii'))+';\n'
    (build.REPO/'waves-data.js').write_text(text, encoding='ascii', newline='\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('stock', type=Path)
    parser.add_argument('--zig', type=Path)
    parser.add_argument('--candidate', type=Path, help='existing exact v9.1 APP1; no compilation')
    parser.add_argument('--out', type=Path, default=build.REPO/'out'/'doom-poly-waves-v9.1-ram')
    parser.add_argument('--web', action='store_true')
    args = parser.parse_args()
    if args.out.exists():
        raise ValueError('refusing to overwrite existing output; choose fresh --out')
    stock = args.stock.read_bytes()
    build.require_hash(stock, build.v2.STOCK_SHA256, 'stock APP1')
    app0 = args.stock.with_name('SP404MKII_APP0.bin').read_bytes()
    build.require_hash(app0, build.APP0_SHA, 'stock APP0')
    if args.candidate:
        _, base = build.build(stock)
        image, info = args.candidate.read_bytes(), verified_sources()
        build.require_hash(image, EXPECTED_SHA, 'existing v9.1 candidate')
    elif args.zig:
        base, image, info = compile_and_build(args.stock.resolve(), args.zig.resolve())
    else:
        parser.error('provide --zig for source reproduction or --candidate for pinned publication')
    if len(image) != EXPECTED_SIZE:
        raise ValueError('invalid candidate size')
    args.out.mkdir(parents=True)
    (args.out/'SP404MKII_APP1.bin').write_bytes(image)
    (args.out/'SP404MKII_APP0.bin').write_bytes(app0)
    (args.out/'manifest.json').write_text(json.dumps(info, indent=2, sort_keys=True)+'\n')
    if args.web:
        publish_overlay(base, image, info)
    print(f'v9.1 APP1: {len(image)} bytes; SHA-256 {build.sha(image)}')
    print('APP0 unchanged; owner reported hardware working; timing remains unmeasured.')


if __name__ == '__main__':
    main()
