"""Publish the exact tested v9.6 overlay, never full Roland firmware.

Requires an existing candidate with its manifest and unchanged stock APP0.
Source reproduction: build_v9.py -> build_scales.py --fixes -> this script.
No network, native DLL execution or device flashing.
"""
import argparse
import base64
import json
from pathlib import Path
import build
import build_v8
import build_v9

HERE=Path(__file__).resolve().parent
EXPECTED_SHA='1b2d50e0cfe20b11bad9cdef6945ec24a14a60e772e56a02dd5478331e275cc9'
EXPECTED_SIZE=2971568
SOURCE_HASHES={
 'scales.c':'f4dfc607e38e5d85cf7b5362a74407d3cefa811254781603e65327f098ecbffa',
 'scales.json':'2c7f6fba266bceccaa2a01c70b9e0c5d2e2a895e5e4d8a0c70cbe6a13deb2d55',
 'voice_fixes.c':'3ae2bb25d63dff92113823ca2aca37574771ef500ae98a2b959cd3d5aa229a3c',
}

def validate(image,info):
    build_v9.verified_sources()
    for name,digest in SOURCE_HASHES.items():
        build.require_hash((HERE/name).read_bytes().replace(b'\r\n',b'\n'),digest,name)
    build.require_hash(image,EXPECTED_SHA,'tested v9.6 APP1')
    if (len(image)!=EXPECTED_SIZE or info['size']!=EXPECTED_SIZE or
        info['sha256']!=EXPECTED_SHA or info['revision']!='v9.6-fixes' or
        info['parent_sha256']!=build_v9.EXPECTED_SHA or
        not info['freq_bounds_fix'] or not info['pad_noteoff_range_fix'] or
        info['scales']!=json.loads((HERE/'scales.json').read_text())):
        raise ValueError('invalid v9.6 metadata')
    for prefix in ('','scale_'):
        off=info[prefix+'code_file']; size=info[prefix+'code_size']
        build.require_hash(image[off:off+size],info[prefix+'module_sha256'],prefix+'module')
    metadata=dict(info,published=True)
    metadata['tests']='59 Unicorn checks pass: 32 v9.5 behavioral, 13 scale and 14 voice-fix checks; byte-exact rebuild confirmed; hardware untested'
    return metadata

def publish_overlay(base,image,info):
    build.require_hash(base,build_v8.BASE_SHA,'browser base')
    info=validate(image,info)
    overlay=build.make_overlay(base,image,'5.52+waves-v9.6')
    if build.apply_container(overlay,base)!=image: raise ValueError('overlay roundtrip differs')
    output='// Generated by synth/publish_v9_6.py; v9.6-fixes, hardware untested.\n'
    output+='window.DOOMOS_WAVES = '+json.dumps(info,sort_keys=True)+';\n'
    output+='window.DOOMOS_WAVES_PATCH = '+json.dumps(base64.b64encode(overlay).decode('ascii'))+';\n'
    (build.REPO/'waves-data.js').write_text(output,encoding='ascii',newline='\n')
    (HERE/'v9_6_manifest.json').write_text(json.dumps(info,sort_keys=True,indent=2)+'\n',encoding='ascii',newline='\n')
    return info

def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('stock',type=Path); ap.add_argument('--candidate',type=Path,required=True)
    args=ap.parse_args()
    stock=args.stock.read_bytes(); build.require_hash(stock,build.v2.STOCK_SHA256,'stock APP1')
    build.require_hash(args.stock.with_name('SP404MKII_APP0.bin').read_bytes(),build.APP0_SHA,'stock APP0')
    build.require_hash(args.candidate.with_name('SP404MKII_APP0.bin').read_bytes(),build.APP0_SHA,'candidate APP0')
    image=args.candidate.read_bytes(); info=json.loads(args.candidate.with_name('manifest.json').read_text())
    validate(image,info) # reject before even composing the frozen base
    _,base=build.build(stock)
    publish_overlay(base,image,info)
    print(f'v9.6 browser overlay verified: {len(image)} bytes; SHA-256 {build.sha(image)}')

if __name__=='__main__': main()
