"""Publish the exact tested v9.9.2 (arpeggiator) overlay, never full Roland firmware.

Requires an existing candidate with its manifest and unchanged stock APP0.
Source reproduction: build_v9.py -> build_scales.py --fixes -> build_arp.py -> this script.
No network, native DLL execution or device flashing.
"""
import argparse
import base64
import json
from pathlib import Path
import build
import build_arp
import build_v8
import build_v9
import publish_v9_6

HERE=Path(__file__).resolve().parent
EXPECTED_SHA='aab582ff45906a4497e59bebabeb4b3dee034f3e94a9dc287aa810ecc809608f'
EXPECTED_SIZE=2984592
SOURCE_HASHES={'arp.c':'d4e5aa6beddd590ee322900b8dc789f84e83571d8241a7d9cfd3d9e8ef9ade46'}
HOOKS=[0x800C19F4,0x800BBC98,0x80123BE6,0x80123CE0,0x8015C7F4,0x8015C85C,0x0001FD84,0x8353B000,0x8005A698]
HARDWARE={'source':'owner hardware reports on the earlier arp builds','date':'2026-10-07',
          'coverage':'earlier arp builds only',
          'detail':('v9.7: menu labels fit, ARP on stops held notes, step timing right. '
                    'v9.9.1: BPM item matched TAP TEMPO with the tempo set to PROJECT, read 90 with BANK '
                    '(the last selected pad\'s bank; v9.9.2 reads the bank on the pads). '
                    'The exact v9.9.2 build is not yet tested on hardware.'),
          'cpu_headroom':'unmeasured'}

def validate(image,info):
    for name,digest in dict(publish_v9_6.SOURCE_HASHES,**SOURCE_HASHES).items():
        build.require_hash((HERE/name).read_bytes().replace(b'\r\n',b'\n'),digest,name)
    build_v9.verified_sources()
    build.require_hash(image,EXPECTED_SHA,'tested v9.9.2 APP1')
    if (len(image)!=EXPECTED_SIZE or info['size']!=EXPECTED_SIZE or
        info['sha256']!=EXPECTED_SHA or info['revision']!='v9.9.2-arp' or
        info['parent_revision']!='v9.6-fixes' or info['parent_sha256']!=publish_v9_6.EXPECTED_SHA or
        info['arp_c_sha256']!=SOURCE_HASHES['arp.c'] or
        [a for a,_ in info['arp_hooks']]!=HOOKS or info['arp_code_base']!=build_arp.MODULE_BASE or
        info['arp_menu']!=build_arp.MENU or
        not info['freq_bounds_fix'] or not info['pad_noteoff_range_fix'] or
        info['scales']!=json.loads((HERE/'scales.json').read_text())):
        raise ValueError('invalid v9.9.2 metadata')
    for prefix in ('','scale_','arp_'):
        off=info[prefix+'code_file']; size=info[prefix+'code_size']
        build.require_hash(image[off:off+size],info[prefix+'module_sha256'],prefix+'module')
    metadata=dict(info,published=True,hardware_validation=HARDWARE)
    metadata['tests']=('67 Unicorn checks pass on the exact build: 21 arp (synth/test_arp.py), the unchanged '
                       '32-check v9.5 suite (synth/test_arp_regression.py) and 14 voice-fix checks; '
                       'byte-exact rebuild confirmed; v9.9.2 hardware untested')
    return metadata

def publish_overlay(base,image,info):
    build.require_hash(base,build_v8.BASE_SHA,'browser base')
    info=validate(image,info)
    overlay=build.make_overlay(base,image,'5.52+arp-v9.9.2')
    if build.apply_container(overlay,base)!=image: raise ValueError('overlay roundtrip differs')
    output='// Generated by synth/publish_v9_9_2.py; v9.9.2-arp, hardware untested.\n'
    output+='window.DOOMOS_WAVES = '+json.dumps(info,sort_keys=True)+';\n'
    output+='window.DOOMOS_WAVES_PATCH = '+json.dumps(base64.b64encode(overlay).decode('ascii'))+';\n'
    (build.REPO/'waves-data.js').write_text(output,encoding='ascii',newline='\n')
    (HERE/'v9_9_2_manifest.json').write_text(json.dumps(info,sort_keys=True,indent=2)+'\n',encoding='ascii',newline='\n')
    return info

def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('stock',type=Path); ap.add_argument('--candidate',type=Path,required=True)
    args=ap.parse_args()
    stock=args.stock.read_bytes(); build.require_hash(stock,build.v2.STOCK_SHA256,'stock APP1')
    build.require_hash(args.stock.with_name('SP404MKII_APP0.bin').read_bytes(),build.APP0_SHA,'stock APP0')
    build.require_hash(args.candidate.with_name('SP404MKII_APP0.bin').read_bytes(),build.APP0_SHA,'candidate APP0')
    image=args.candidate.read_bytes(); info=json.loads(args.candidate.with_name('manifest.json').read_text())
    validate(image,info) # reject before even composing the frozen base
    _,base=build.build(stock)
    publish_overlay(base,image,info)
    print(f'v9.9.2 browser overlay verified: {len(image)} bytes; SHA-256 {build.sha(image)}')

if __name__=='__main__': main()
